/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/disco-balls-590520664b2c4486a7ab36d4fc6f6136
Title: Disco Balls
*/
import balls from "../assets/assets/3d/balls.glb";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations, Environment, OrbitControls } from "@react-three/drei";
import { a } from "@react-spring/three";
import { useThree } from "@react-three/fiber";


const Balls = (props) => {

  const group = useRef();
  const { nodes, materials, animations } = useGLTF(balls);
  const { actions } = useAnimations(animations, group);
  const actionRef = useRef();

  useEffect(() => {
    if (actions && actions["Animation"]) {
      actionRef.current = actions["Animation"];
      actionRef.current.play();
    }
  }, [actions]);

  return (

    <><>
    <a.group ref={group} {...props} dispose={null} position={[0.5, 1, 0]} scale={0.2}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Sphere_0"
                position={[-3.059, -0.665, -22.013]}
                scale={0.334}
              >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere001_1" position={[-8.202, 0, -48.479]}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere002_2" position={[-6, 0, -16]}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere003_3"
                position={[1.131, 2.388, -71.028]}
                scale={3.382}
              >
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere004_4"
                position={[-8.983, 0.926, -29.371]}
                scale={1.929}
              >
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere005_5"
                position={[5.506, -0.665, -17.022]}
                scale={0.334}
              >
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere006_6"
                position={[-9.827, -0.665, -27.967]}
                scale={0.334}
              >
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere007_7" position={[8.301, 0.005, -31.784]}>
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere008_8" position={[5.766, 0, -16.806]}>
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere009_9"
                position={[-0.04, 0.926, -24.134]}
                scale={1.929}
              >
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere010_10"
                position={[8.828, -0.665, -15.085]}
                scale={0.334}
              >
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere011_11"
                position={[8.83, 0.926, -45.526]}
                scale={1.929}
              >
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere012_12" position={[-3, 0, -16]}>
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere013_13"
                position={[4.178, -0.665, -27.738]}
                scale={0.334}
              >
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere014_14"
                position={[-3.059, -0.665, -0.599]}
                rotation={[0.126, 0, 0]}
                scale={0.334}
              >
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere015_15"
                position={[-8.202, 0, -16.399]}
                rotation={[0.063, 0, 0]}
              >
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere016_16"
                position={[-6, 0, 0.04]}
                rotation={[0.031, 0, 0]}
              >
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere017_17"
                position={[1.131, 2.388, -16.774]}
                rotation={[0.031, 0, 0]}
                scale={3.382}
              >
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere018_18"
                position={[-8.983, 0.926, 1.571]}
                rotation={[0.031, 0, 0]}
                scale={1.929}
              >
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere019_19"
                position={[5.506, -0.665, 4.392]}
                rotation={[0.126, 0, 0]}
                scale={0.334}
              >
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere020_20"
                position={[-9.827, -0.665, -6.553]}
                rotation={[0.126, 0, 0]}
                scale={0.334}
              >
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere021_21"
                position={[8.301, -0.003, 0.256]}
                rotation={[0.063, 0, 0]}
              >
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere022_22"
                position={[5.766, 0, -0.766]}
                rotation={[0.031, 0, 0]}
              >
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere023_23"
                position={[-0.04, 0.926, 6.809]}
                rotation={[0.031, 0, 0]}
                scale={1.929}
              >
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere024_24"
                position={[8.828, -0.665, 6.329]}
                rotation={[0.126, 0, 0]}
                scale={0.334}
              >
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere025_25"
                position={[8.83, 0.926, -14.584]}
                rotation={[0.031, 0, 0]}
                scale={1.929}
              >
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere026_26"
                position={[-3, 0, 16.08]}
                rotation={[0.063, 0, 0]}
              >
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere027_27"
                position={[4.178, -0.665, -6.324]}
                rotation={[0.126, 0, 0]}
                scale={0.334}
              >
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere028_28"
                position={[-3.059, -0.665, -22.013]}
                scale={0.334}
              >
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere029_29" position={[-8.202, 0, -48.479]}>
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere030_30" position={[-6, 0, -16]}>
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere031_31"
                position={[1.131, 2.388, -71.028]}
                scale={3.382}
              >
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere032_32"
                position={[-8.983, 0.926, -29.371]}
                scale={1.929}
              >
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere033_33"
                position={[5.506, -0.665, -17.022]}
                scale={0.334}
              >
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere034_34"
                position={[-9.827, -0.665, -27.967]}
                scale={0.334}
              >
                <mesh
                  name="Object_72"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere035_35" position={[8.301, 0.005, -31.844]}>
                <mesh
                  name="Object_74"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere036_36" position={[5.766, 0, -16.806]}>
                <mesh
                  name="Object_76"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere037_37"
                position={[-0.04, 0.926, -24.134]}
                scale={1.929}
              >
                <mesh
                  name="Object_78"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere038_38"
                position={[8.828, -0.665, -15.085]}
                scale={0.334}
              >
                <mesh
                  name="Object_80"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere039_39"
                position={[8.83, 0.926, -45.526]}
                scale={1.929}
              >
                <mesh
                  name="Object_82"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere040_40" position={[-3, 0, -16]}>
                <mesh
                  name="Object_84"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Sphere041_41"
                position={[4.178, -0.665, -27.738]}
                scale={0.334}
              >
                <mesh
                  name="Object_86"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_86.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Cube_87"
                position={[0.001, 2.701, 0.026]}
                rotation={[0, 0, Math.PI]}
              >
               
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
    </>
    <Environment preset="studio" background={false}/>
    <pointLight position={[0, 0, -10]} intensity={70} />
          <pointLight position={[0, 10, 0]} intensity={70} />
          <ambientLight intensity={0.4} />
          <OrbitControls enablePan={false} enableRotate={false} enableZoom={false}  />
    </>
  );
}

export default Balls;
