/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BlueMesh (https://sketchfab.com/VapTor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/s9-mini-drone-cf3ed83c1b87486d90435f54c074e16e
Title: S9 Mini Drone
*/

import { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";
import drone3d from "../assets/assets/3d/drone.glb";

const Drone = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(drone3d);
  const { actions } = useAnimations(animations, group);
  return (
    <a.group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Circle" position={[1.378, 1.984, 0.607]} scale={0.421}>
              <mesh
                name="Circle_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle_0.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                name="Circle_1"
                castShadow
                receiveShadow
                geometry={nodes.Circle_1.geometry}
                material={materials["Material.003"]}
              />
            </group>
            <group name="Circle001" position={[3.077, 2.731, -0.052]}>
              <mesh
                name="Circle001_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle001_0.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                name="Circle001_1"
                castShadow
                receiveShadow
                geometry={nodes.Circle001_1.geometry}
                material={materials["Material.003"]}
              />
            </group>
            <group
              name="Cube"
              position={[0.016, 0.269, 0]}
              scale={[1.181, 1, 1]}
            >
              <mesh
                name="Cube_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube_0.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                name="Cube_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube_1.geometry}
                material={materials["Material.002"]}
              />
            </group>
            <group
              name="Sphere"
              position={[0.048, 2.873, -0.188]}
              scale={[0.096, 0.096, 0.121]}
            >
              <mesh
                name="Sphere_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere_0.geometry}
                material={materials["Material.005"]}
              />
            </group>
            <group
              name="Sphere001"
              position={[-0.002, -2.487, -0.124]}
              scale={[0.174, 0.13, 0.163]}
            >
              <mesh
                name="Sphere001_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere001_0.geometry}
                material={materials["Material.004"]}
              />
            </group>
            <group
              name="Cube001"
              position={[1.136, 0.834, 0.278]}
              scale={[0.101, 0.05, 0.05]}
            >
              <mesh
                name="Cube001_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube001_0.geometry}
                material={materials["Cylinder.001_0"]}
              />
            </group>
            <group
              name="Circle002"
              position={[3.059, 2.733, 1.004]}
              rotation={[0, 0, 0.052]}
              scale={0.147}
            >
              <mesh
                name="Circle002_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle002_0.geometry}
                material={materials.pale}
              />
            </group>
            <group
              name="Circle003"
              position={[-3.035, 2.754, 1.004]}
              rotation={[0, 0, -1.435]}
              scale={0.147}
            >
              <mesh
                name="Circle003_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle003_0.geometry}
                material={materials.pale}
              />
            </group>
            <group
              name="Circle004"
              position={[-3.035, -2.19, 1.004]}
              rotation={[0, 0, -0.391]}
              scale={0.147}
            >
              <mesh
                name="Circle004_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle004_0.geometry}
                material={materials.pale}
              />
            </group>
            <group
              name="Circle005"
              position={[3.047, -2.187, 1.004]}
              rotation={[0, 0, -1.36]}
              scale={0.147}
            >
              <mesh
                name="Circle005_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle005_0.geometry}
                material={materials.pale}
              />
            </group>
            <group
              name="Cylinder"
              position={[0.057, 3.094, 0.252]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.122}
            >
              <mesh
                name="Cylinder_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_0.geometry}
                material={materials["Cylinder.001_0"]}
              />
            </group>
            <group
              name="Cylinder001"
              position={[-0.06, 3.094, 0.252]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.122}
            >
              <mesh
                name="Cylinder001_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001_0.geometry}
                material={materials["Cylinder.001_0"]}
              />
            </group>
            <group
              name="Circle006"
              position={[0.003, 0.457, -4.295]}
              scale={12.303}
            >
              <mesh
                name="Circle006_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle006_0.geometry}
                material={materials["Material.006"]}
              />
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
}

export default Drone;